services:
  - type: web
    name: chronos-work-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run migration:run:prod && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: chronos-work-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: chronos-work-db
    databaseName: chronos_work
    plan: free
    region: oregon
